// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZeCg43xPndyXH03YxlTW0t5dAxeZNBs',
    appId: '1:195138054780:web:7cdb3722e59210584b77f9',
    messagingSenderId: '195138054780',
    projectId: 'appgoodlife-31425',
    authDomain: 'appgoodlife-31425.firebaseapp.com',
    storageBucket: 'appgoodlife-31425.firebasestorage.app',
    measurementId: 'G-XQM193TX7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5bc2Wlhm9ExxysUYKKusqtdhq2gFj6k',
    appId: '1:195138054780:android:17e052aa9b4341614b77f9',
    messagingSenderId: '195138054780',
    projectId: 'appgoodlife-31425',
    storageBucket: 'appgoodlife-31425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUjtRhMhI7W2SU5lBJuOp8D7pWlOAUL4',
    appId: '1:195138054780:ios:7856a4333f1bb9a24b77f9',
    messagingSenderId: '195138054780',
    projectId: 'appgoodlife-31425',
    storageBucket: 'appgoodlife-31425.firebasestorage.app',
    iosBundleId: 'com.example.appgoodlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBUjtRhMhI7W2SU5lBJuOp8D7pWlOAUL4',
    appId: '1:195138054780:ios:7856a4333f1bb9a24b77f9',
    messagingSenderId: '195138054780',
    projectId: 'appgoodlife-31425',
    storageBucket: 'appgoodlife-31425.firebasestorage.app',
    iosBundleId: 'com.example.appgoodlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaZeCg43xPndyXH03YxlTW0t5dAxeZNBs',
    appId: '1:195138054780:web:933489b909c549e14b77f9',
    messagingSenderId: '195138054780',
    projectId: 'appgoodlife-31425',
    authDomain: 'appgoodlife-31425.firebaseapp.com',
    storageBucket: 'appgoodlife-31425.firebasestorage.app',
    measurementId: 'G-FE3X749NM8',
  );
}
