<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cajacentral extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $table = 'cajacentral';
    static $rules = [
        'id' => '',
        'tipocliente' => '',
        'clienteid' => '',
        'clientenombre' => '',
        'proveedorid' => '',
        'proveedornombre' => '',
        'clienteauditoriaid' => '',
        'clienteauditorianombre' => '',
        'clientecomunid' => '',
        'clientecomunnombre' => '',
        'clientebancoid' => '',
        'clientebanconombre' => '',
        'detalle' => '',
        'area' => '',
        'subtotal' => '',
        'descuento' => '',
        'montototal' => '',
        'saldo' => '',
        'nrorecibo' => '',
        'nrofactura' => '',
        'nrobancarizaciondeposito' => '',
        'nrobancarizaciontransferencia' => '',
        'nrocheque' => '',
        'nrotarjeta' => '',
        'nroap' => '',
        'nroref' => '',
        'nrocuentadestinodeposito' => '',
        'nrocuentaorigendeposito' => '',
        'tipobancodeposito' => '',
        'nrocuentadestinotransferencia' => '',
        'nrocuentadestinocheque' => '',
        'nrocuentaorigentransferencia' => '',
        'tipobancotransferencia' => '',
        'tipobancocheque' => '',
        'tipocambio' => '',
        'tipomovimiento' => '',
        'tipotransaccion' => '',
        'tipotransaccion2' => '',
        'ciudadregistro' => '',
        'estado' => '',
        'usuariorevisioncierre' => '',
        'estadorevisioncierre' => '',
        'estadorevisioncierreegreso' => '',
        'usuarioregistronombre' => '',
        'nombrebanco' => '',
        'numerobanco' => '',
        'usuarioregistroid' => '',
        'usuarioactualizacion' => '',
        'usuarioanulacion' => '',
        'documentorespaldo' => '',
        'docrespaldoegreso' => '',
        'fechacierre' => '',
        'usuariocierrecaja' => '',
        'motivoanulacion' => '',
        'diferenciafavor' => '',
        'diferenciacontra' => '',
        'montopago' => '',
        'montodevuelto' => '',
        'descuentoatc' => '',
        'montorealatc' => '',
        'nrobancarizacionatc' => '',
        'docfactura' => '',
        'doccomprobante' => '',
        'nrobancarizacionefectivo' => '',
        'nrobancodestinoefectivo' => '',
        'nrofactura2' => '',
        'nrofactura3' => '',
    ]; 

    protected $fillable = [
        'id',
        'tipocliente',
        'clienteid',
        'clientenombre',
        'proveedorid',
        'proveedornombre',
        'clienteauditoriaid',
        'clienteauditorianombre',
        'clientecomunid',
        'clientecomunnombre',
        'clientebancoid',
        'clientebanconombre',
        'detalle',
        'area',
        'subtotal',
        'descuento',
        'montototal',
        'saldo',
        'nrorecibo',
        'nrofactura',
        'nrobancarizaciondeposito',
        'nrobancarizaciontransferencia',
        'nrocheque',
        'nrotarjeta',
        'nroap',
        'nroref',
        'nrocuentadestinodeposito',
        'nrocuentaorigendeposito',
        'tipobancodeposito',
        'nrocuentadestinotransferencia',
        'nrocuentadestinocheque',
        'nrocuentaorigentransferencia',
        'tipobancotransferencia',
        'tipobancocheque',
        'tipocambio',
        'tipomovimiento',
        'tipotransaccion',
        'tipotransaccion2',
        'ciudadregistro',
        'estado',
        'usuariorevisioncierre',
        'estadorevisioncierre',
        'estadorevisioncierreegreso',
        'usuarioregistronombre',
        'nombrebanco',
        'numerobanco',
        'usuarioregistroid',
        'usuarioactualizacion',
        'usuarioanulacion',
        'documentorespaldo',
        'docrespaldoegreso',
        'fechacierre',
        'usuariocierrecaja',
        'motivoanulacion',
        'diferenciafavor',
        'diferenciacontra',
        'montopago',
        'montodevuelto',
        'descuentoatc',
        'montorealatc',
        'nrobancarizacionatc',
        'docfactura',
        'doccomprobante',
        'nrobancarizacionefectivo',
        'nrobancodestinoefectivo',
        'nrofactura2',
        'nrofactura3',
    ];
}
