<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tramite extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'procedimientotramites';
    static $rules = [
        'id' => '',
        'idtramite' => '',
        'clienteid' => '',
        'clientenombre' => '',
        'nivelprocedimiento' => '',
        'subprocedimiento' => '',
        'document' => '',
        'document2' => '',
        'document3' => '',
        'document4' => '',
        'document5' => '',
        'document6' => '',
        'observaciones' => '',
        'apoderado' => '',
        'fechasubida' => '',
        'horasubida' => '',
        'fechaviaje' => '',
        'horaviaje' => '',
        'tramite' => '',
        'seguro' => '',
        'usuarioid' => '',
        'usuarioregistro' => '',
        'estadodictamen' => '',
        'porcentajeriesgodictamen' => '',
        'viaja' => '',
        'departamentoviaja' => '',

        'fechagestoradictamen' => '',
        'fechasinestro' => '',
        'fechacobrocontrato' => '',
        'montocontrato' => '',
        'motivorechazo' => '',
        'notaseguimiento' => '',
        'estadocomunicado' => '',
        'riesgodictamen' => '',
        'tiporiesgodictamen' => '',
        'mescierre' => '',
        'usuarioingreso' => '',
        'tipodocumento' => '',
        'estadotramite' => '',
        'fechacitenotificacion' => '',
        'fechacitenota' => '',
        'tipomedico' => '',
        'nombremedico' => '',
        'citenotificacion' => '',
        'citenota' => '',
        'motivonoseguro' => '',
        'nombremedico2' => '',
        'nombremedico3' => '',
        'fecharetorno' => '',
        'recojodocumentacion' => '',
        'fechainclusion' => '',
        'fechaestadotramite' => '',
        'tipodocumentacion' => '',
        'corsolicitud' => '',
        'opcioncorsolicitud' => '',
        'tipo' => '',
        'nro' => '',
        'decisionviaja' => '',
        'transporteviaja' => '',
        'viaticos' => '',
        'nrodictamen' => '',
        'nroformulario' => '',
        'accesopension' => '',
        'motivonopension' => '',
        'mescobro' => '',
        'tipocarta' => '',

        'comusuemisor' => '',
        'comusureceptor' => '',
        'commodo' => '',
        'comtipointerac' => '',
        'comdetalle' => '',
        'comtipoentrega' => '',
        'comtipodoc' => '',
        'nombremedico4' => '',
        'nombremedico5' => '',
        'capturacomunicacion' => '',
    ]; 

    protected $fillable = [
        'id',
        'idtramite',
        'clienteid',
        'clientenombre',
        'nivelprocedimiento',
        'subprocedimiento',
        'document',
        'document2',
        'document3',
        'document4',
        'document5',
        'document6',
        'observaciones',
        'apoderado',
        'fechasubida',
        'horasubida',
        'fechaviaje',
        'horaviaje',
        'tramite',
        'seguro',
        'usuarioid',
        'usuarioregistro',
        'estadodictamen',
        'porcentajeriesgodictamen',
        'viaja',
        'departamentoviaja',

        'fechagestoradictamen',
        'fechasinestro',
        'fechacobrocontrato',
        'montocontrato',
        'motivorechazo',
        'notaseguimiento',
        'estadocomunicado',
        'riesgodictamen',
        'tiporiesgodictamen',
        'mescierre',
        'usuarioingreso',
        'tipodocumento',
        'estadotramite',
        'fechacitenotificacion',
        'fechacitenota',
        'tipomedico',
        'nombremedico',
        'citenotificacion',
        'citenota',
        'motivonoseguro',
        'nombremedico2',
        'nombremedico3',
        'fecharetorno',
        'recojodocumentacion',
        'fechainclusion',
        'fechaestadotramite',
        'tipodocumentacion',
        'corsolicitud',
        'opcioncorsolicitud',
        'tipo',
        'nro',
        'decisionviaja',
        'transporteviaja',
        'viaticos',
        'nrodictamen',
        'nroformulario',
        'accesopension',
        'motivonopension',
        'mescobro',
        'tipocarta',

        'comusuemisor',
        'comusureceptor',
        'commodo',
        'comtipointerac',
        'comdetalle',
        'comtipoentrega',
        'comtipodoc',
        'nombremedico4',
        'nombremedico5',
        'capturacomunicacion',
    ];

    public function areaaccion()
    {
        return $this->hasMany(AreaAccion::class, 'areasid', 'id');
    }
    

}
